Repository KU-Barrier-Free/KU-Barrier-Free-Server, pull requests merged in 2025-08, with the labels that each got.

#28 [Docs] #27 README.md 파일 업데이트
  README.md
Labels: 상균

#36 [Feat] 건물 또는 편의시설 검색 기능 구현
  src/main/java/com/example/BarrierKU/domain/building/dto/BuildingResponse.java
  src/main/java/com/example/BarrierKU/domain/building/repository/BuildingRepository.java
  src/main/java/com/example/BarrierKU/domain/building/service/BuildingService.java
  src/main/java/com/example/BarrierKU/domain/facility/dto/FacilitiesResponse.java
  src/main/java/com/example/BarrierKU/domain/facility/repository/FacilityRepository.java
  src/main/java/com/example/BarrierKU/domain/facility/service/FacilityService.java
  src/main/java/com/example/BarrierKU/domain/place/controller/PlaceController.java
  src/main/java/com/example/BarrierKU/domain/place/dto/PlaceSearchResponse.java
  src/main/java/com/example/BarrierKU/domain/place/dto/SearchBuildingResponse.java
  src/main/java/com/example/BarrierKU/domain/place/dto/SearchFacilityWithBuildingResponse.java
  src/main/java/com/example/BarrierKU/domain/place/service/PlaceService.java
  src/main/resources/application.yml
Labels: 영선

#31 [Feat] 장애학생지원센터 공지사항 크롤링
  build.gradle
  src/main/java/com/example/BarrierKU/common/response/ResponseCode.java
  src/main/java/com/example/BarrierKU/common/swagger/SwaggerResponseDescription.java
  src/main/java/com/example/BarrierKU/domain/image/Image.java
  src/main/java/com/example/BarrierKU/domain/supportcenter/controller/SupportCenterController.java
  src/main/java/com/example/BarrierKU/domain/supportcenter/dto/NoticeResponse.java
  src/main/java/com/example/BarrierKU/domain/supportcenter/service/NoticeService.java
Labels: 홍준

#39 [Feat] 길 찾기 API 구현
  .gitignore
  src/main/java/com/example/BarrierKU/common/response/ResponseCode.java
  src/main/java/com/example/BarrierKU/common/swagger/SwaggerResponseDescription.java
  src/main/java/com/example/BarrierKU/domain/door/repository/DoorRepository.java
  src/main/java/com/example/BarrierKU/domain/path/controller/PathController.java
  src/main/java/com/example/BarrierKU/domain/path/dto/GeoJsonFeature.java
  src/main/java/com/example/BarrierKU/domain/path/dto/GeoJsonFeatureCollection.java
  src/main/java/com/example/BarrierKU/domain/path/dto/GraphEdge.java
  src/main/java/com/example/BarrierKU/domain/path/dto/PathRecommendationsResponse.java
  src/main/java/com/example/BarrierKU/domain/path/factory/GeoJsonFactory.java
  src/main/java/com/example/BarrierKU/domain/path/factory/PathSqlFactory.java
  src/main/java/com/example/BarrierKU/domain/path/model/Crossing.java
  src/main/java/com/example/BarrierKU/domain/path/model/Node.java
  src/main/java/com/example/BarrierKU/domain/path/model/PathType.java
  src/main/java/com/example/BarrierKU/domain/path/model/Street.java
  src/main/java/com/example/BarrierKU/domain/path/model/Way.java
  src/main/java/com/example/BarrierKU/domain/path/repository/CrossingRepository.java
  src/main/java/com/example/BarrierKU/domain/path/repository/NodeRepository.java
  src/main/java/com/example/BarrierKU/domain/path/repository/StreetRepository.java
  src/main/java/com/example/BarrierKU/domain/path/repository/WayRepository.java
  src/main/java/com/example/BarrierKU/domain/path/service/DataLoadingService.java
  src/main/java/com/example/BarrierKU/domain/path/service/PathService.java
Labels: 상균

#48 [Fix] 데이터 업로드 과정에서 엔티티 필드 불일치 수정
  .gitignore
  src/main/java/com/example/BarrierKU/domain/door/dto/DoorInfo.java
  src/main/java/com/example/BarrierKU/domain/indoor/Building.java
  src/main/java/com/example/BarrierKU/domain/indoor/Door.java
  src/main/java/com/example/BarrierKU/domain/type/ImageType.java
  src/main/java/com/example/BarrierKU/domain/type/Purpose.java
Labels: 영선
